# Generated by Django 5.2.5 on 2025-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount_off',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
