# Generated by Django 5.2.5 on 2025-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_discount_amount_off_alter_discount_percent_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount_off',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
