# Generated by Django 5.2.5 on 2025-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_discount_stripe_coupon_id_tax_stripe_tax_rate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'usd'), ('EUR', 'eur')], max_length=20),
        ),
    ]
